PoliziaMunicipale/Controllers/TrasgressoreController.cs
using Microsoft.Ajax.Utilities;
using PoliziaMunicipale.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PoliziaMunicipale.Controllers
{
    public class TrasgressoreController : Controller
    {
        // GET: Trasgressore
       public ActionResult Create()
        {
            ViewBag.AllTrasgressori = DB.getAllTrasgressori();
            return View();
        }
        [HttpPost]
        public ActionResult Create(Trasgressore t)
        {
            if (ModelState.IsValid)
            {
                DB.AggiungiTrasgressore(t.Surname, t.Name, t.Address, t.City, t.CAP, t.CF);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.AllTrasgressori = DB.getAllTrasgressori();
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            Trasgressore t = DB.getTrasgressoreById(id);
            return View(t);
        }
        [HttpPost]
        public ActionResult Edit(Trasgressore t)
        {
            if (ModelState.IsValid)
            {
                DB.UpdateTrasgressore(t.Id, t.Surname, t.Name, t.Address, t.City, t.CAP, t.CF);
                return RedirectToAction("Index", "Home");
            }
            else return View(t);
        }

        public ActionResult Delete(int id)
        {
            DB.RemoveTrasgressore(id); 
            return RedirectToAction("Index","Home");
        }

    }
}

PoliziaMunicipale/Controllers/VerbaleController.cs
using PoliziaMunicipale.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PoliziaMunicipale.Controllers
{
    public class VerbaleController : Controller
    {
        // GET: Verbale
        public List<Trasgressore> t = DB.getAllTrasgressori();
        public List<Violazione> v = DB.getAllViolazioni();
        public List<SelectListItem> trasgressori
        {
            get
            {
                List<SelectListItem> listT = new List<SelectListItem>();
                foreach (Trasgressore tr in t)
                {
                    SelectListItem item = new SelectListItem { Text= tr.Surname +" "+ tr.Name, Value = tr.Id.ToString()};
                    listT.Add(item);
                }
                return listT;
            }
        }
        public List<SelectListItem> violazioni
        {
            get
            {
                List<SelectListItem> listV = new List<SelectListItem>();
                foreach (Violazione vi in v)
                {
                    SelectListItem item = new SelectListItem { Text = vi.Description, Value = vi.Id.ToString() };
                    listV.Add(item);
                }
                return listV;
            }
        }
        public ActionResult Create()
        {
            ViewBag.ListaTrasgressori = trasgressori;
            ViewBag.ListaViolazioni = violazioni;
            ViewBag.ListaVerbali = DB.getAllVerbali();
            return View();
        }
        [HttpPost]
        public ActionResult Create(Verbale v)
        {
            if (ModelState.IsValid)
            {
                DB.AggiungiVerbale(v.DataViolazione, v.IndirizzoViolazione, v.Agente, v.DataVerbale, v.Importo, v.PuntiTolti, v.IdTrasgressore, v.IdViolazione);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ListaTrasgressori = trasgressori;
                ViewBag.ListaViolazioni = violazioni;
                ViewBag.ListaVerbali = DB.getAllVerbali();
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            ViewBag.ListaTrasgressori = trasgressori;
            ViewBag.ListaViolazioni = violazioni;
            Verbale v = DB.getVerbaleById(id);
            return View(v);
        }

        [HttpPost]
        public ActionResult Edit(Verbale v)
        {
            if (ModelState.IsValid)
            {
                DB.UpdateVerbale(v.Id, v.DataViolazione, v.IndirizzoViolazione, v.Agente, v.DataVerbale, v.Importo, v.PuntiTolti, v.IdTrasgressore, v.IdViolazione);
                return RedirectToAction("Index", "Home");
            } else return View(v); 
        }

        public ActionResult Remove(int id)
        {
            DB.RemoveVerbale(id); 
            return RedirectToAction("Index","Home");
        }
    }
}

PoliziaMunicipale/Controllers/ViolazioneController.cs
using PoliziaMunicipale.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PoliziaMunicipale.Controllers
{
    public class ViolazioneController : Controller
    {
        // GET: Violazione
        public ActionResult Create()
        {
            ViewBag.AllViolazioni = DB.getAllViolazioni();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Violazione v)
        {
            if (ModelState.IsValid)
            {
                DB.AggiungiViolazione(v.Description);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.AllViolazioni = DB.getAllViolazioni();
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            Violazione v = DB.getViolazioneById(id);
            return View(v);
        }
        [HttpPost]
        public ActionResult Edit(Violazione v)
        {
            if(ModelState.IsValid)
            {
                DB.UpdateViolazione(v.Id,v.Description);
                return RedirectToAction("Index","Home");
            } else return View(v);
        }

        public ActionResult Delete(int id)
        {
            DB.RemoveViolazione(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

PoliziaMunicipale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark text-bg-primary">
        <div class="container">
            <img src="~/Content/assets/stemma.jpg" width="30" class="mx-2" />
            @Html.ActionLink("POLIZIA MUNICIPALE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand active" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Aggiungi Trasgressore", "Create", "Trasgressore", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Aggiungi Violazione", "Create", "Violazione", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Aggiungi Verbale", "Create", "Verbale", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content my-5">
        @RenderBody()
        <hr />
        <footer class="py-2">
            <p>&copy; @DateTime.Now.Year - Dirigente Dipartimento: Giuseppe Cifarelli</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>